export type RootStackParamList = {
  Splash: undefined;
  Onboarding: undefined;
  SelectMethod: undefined;
  Otp: { method: 'phone' | 'email'; value: string };
  Login: undefined;
  ContinueSignUp: undefined;
  ContinueBoarding: undefined;
  Home: undefined;
  CustomerDashboard: undefined;
  DriverHome: undefined;
  DriverDashboard: undefined;
  AddLocation: undefined;
  OrderTracking: { orderId: string; eta?: string };
  RateOrder: { orderId: string; rating?: number; review?: string };
  ProductScreen: undefined;
  RestaurantDetail: { restaurant: any };
  ProductDetail: { product: any };
  Cart: undefined;
  Checkout: undefined;
  DriverOrders: undefined;
  DriverRoutes: undefined;
  DriverEarnings: undefined;
  DriverSetting: undefined;
  EditProduct: undefined;
  EditPromotion: undefined;
  EditCategory: undefined;
  CreatePromotion: undefined;
  CreateCategory: undefined;
  CreateBrand: undefined;
  PreviewPromotion: undefined;
  Profile: undefined;
  VendorTabs: undefined;
  VendorDashboard: undefined;
  VendorProducts: undefined;
  VendorReports: undefined;
  VendorNotifications: undefined;
  VendorProfile: undefined;
  OrderDeliveryFirstStep: undefined;
  OrderDeliverySecondStep: undefined;
  OrderDeliveryLastStep: undefined;
  DriverProfile: undefined;
};
